### ISSUE TITLE
Excel sheet project structuring

### ISSUE THREAD

**Issue by blakewatanabe** [manoa-inspire/MATP#20]
Please do work for this task in a branch called issue-20.

Implement the formulas that Spire uses to produce results:

- Grabs the requested financial data from the database
- Implement the formula(s) with the input being the financial data
- Generate the desired outcome of the formulas

**Comment by TannerBerry** [comment]
File sturctures set up and commited to main regarding inputs/outputs/an formula sheets. File auditBalanceSheet is finished to be used as verification that this sturcteral method is acceptable.
